# PowerShell script to create Gradle wrapper files
Write-Host "Setting up Gradle wrapper..."

# Remove old files if exist
if (Test-Path "gradlew") { Remove-Item "gradlew" -Force }
if (Test-Path "gradlew.bat") { Remove-Item "gradlew.bat" -Force }

# Create gradlew (Unix/Linux/Mac script)
$gradlewContent = @'
#!/bin/sh

##############################################################################
##
##  Gradle start up script for POSIX generated by Gradle.
##
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    app_path=$link  # append to the path
done

APP_HOME=$( cd "${APP_HOME:-./}" > /dev/null && pwd -P ) || exit

APP_NAME="Gradle"
APP_BASE_NAME=${0##*/}

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(-
  CYGWIN* )         cygwin=true  ;; #(-
  Darwin* )         darwin=true  ;; #(-
  MSYS* | MINGW* )  msys=true    ;; #(-
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(-
      max*)
        MAX_FD=$( ulimit -h -n ) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case $MAX_FD in  #(-
      '' | soft) :;; #(-
      *)
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to $MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )
fi

exec "$JAVACMD" \
    $DEFAULT_JVM_OPTS \
    $JAVA_OPTS \
    $GRADLE_OPTS \
    "-Dorg.gradle.appname=$APP_BASE_NAME" \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"
'@

# Create gradlew.bat (Windows script)
$gradlewBatContent = @'
@rem
@rem Copyright 2015 the original author or authors.
@rem
@rem Licensed under the Apache License, Version 2.0 (the "License");
@rem you may not use this file except in compliance with the License.
@rem You may obtain a copy of the License at
@rem
@rem      https://www.apache.org/licenses/LICENSE-2.0
@rem
@rem Unless required by applicable law or agreed to in writing, software
@rem distributed under the License is distributed on an "AS IS" BASIS,
@rem WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
@rem See the License for the specific language governing permissions and
@rem limitations under the License.
@rem

@if "%DEBUG%"=="" @echo off
@rem ##########################################################################
@rem
@rem  Gradle startup script for Windows
@rem
@rem ##########################################################################

@rem Set local scope for the variables with windows NT shell
if "%OS%"=="Windows_NT" setlocal

set DIRNAME=%~dp0
if "%DIRNAME%"=="" set DIRNAME=.
@rem This is normally unused
set APP_BASE_NAME=%~n0
set APP_HOME=%DIRNAME%

@rem Resolve any "." and ".." in APP_HOME to make it shorter.
for %%i in ("%APP_HOME%") do set APP_HOME=%%~fi

@rem Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
set DEFAULT_JVM_OPTS="-Xmx64m" "-Xms64m"

@rem Find java.exe
if defined JAVA_HOME goto findJavaFromJavaHome

set JAVA_EXE=java.exe
%JAVA_EXE% -version >NUL 2>&1
if %ERRORLEVEL% equ 0 goto execute

echo.
echo ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
echo.
echo Please set the JAVA_HOME variable in your environment to match the
echo location of your Java installation.

goto fail

:findJavaFromJavaHome
set JAVA_HOME=%JAVA_HOME:"=%
set JAVA_EXE=%JAVA_HOME%/bin/java.exe

if exist "%JAVA_EXE%" goto execute

echo.
echo ERROR: JAVA_HOME is set to an invalid directory: %JAVA_HOME%
echo.
echo Please set the JAVA_HOME variable in your environment to match the
echo location of your Java installation.

goto fail

:execute
@rem Setup the command line

set CLASSPATH=%APP_HOME%\gradle\wrapper\gradle-wrapper.jar


@rem Execute Gradle
"%JAVA_EXE%" %DEFAULT_JVM_OPTS% %JAVA_OPTS% %GRADLE_OPTS% "-Dorg.gradle.appname=%APP_BASE_NAME%" -classpath "%CLASSPATH%" org.gradle.wrapper.GradleWrapperMain %*

:end
@rem End local scope for the variables with windows NT shell
if %OS%==Windows_NT endlocal

:omega

:fail
rem Set variable GRADLE_EXIT_CONSOLE if you need the _script_ return code instead of
rem the _cmd.exe /c_ return code!
set EXIT_CODE=%ERRORLEVEL%
if %EXIT_CODE% equ 0 set EXIT_CODE=1
if not ""=="%GRADLE_EXIT_CONSOLE%" exit %EXIT_CODE%
exit /b %EXIT_CODE%
'@

# Write files
Write-Host "Creating gradlew..."
[System.IO.File]::WriteAllText("$PWD\gradlew", $gradlewContent, [System.Text.UTF8Encoding]::new($false))

Write-Host "Creating gradlew.bat..."
[System.IO.File]::WriteAllText("$PWD\gradlew.bat", $gradlewBatContent, [System.Text.UTF8Encoding]::new($false))

# Download gradle-wrapper.jar
Write-Host "Downloading gradle-wrapper.jar..."
$url = "https://raw.githubusercontent.com/gradle/gradle/v8.9.0/gradle/wrapper/gradle-wrapper.jar"
$output = "gradle\wrapper\gradle-wrapper.jar"

try {
    Invoke-WebRequest -Uri $url -OutFile $output -UseBasicParsing
    Write-Host "Successfully downloaded gradle-wrapper.jar"
} catch {
    Write-Host "Error downloading from primary URL: $_"
    Write-Host "Trying alternative approach..."
    
    # Download full Gradle distribution and extract wrapper jar
    $url2 = "https://services.gradle.org/distributions/gradle-8.9-bin.zip"
    $tempZip = "$env:TEMP\gradle-8.9-bin.zip"
    $tempDir = "$env:TEMP\gradle-8.9"
    
    try {
        Write-Host "Downloading Gradle distribution (this may take a minute)..."
        Invoke-WebRequest -Uri $url2 -OutFile $tempZip -UseBasicParsing
        
        Write-Host "Extracting gradle-wrapper.jar..."
        Expand-Archive -Path $tempZip -DestinationPath $tempDir -Force
        
        $wrapperJar = Get-ChildItem -Path $tempDir -Recurse -Filter "gradle-wrapper.jar" | Select-Object -First 1
        if ($wrapperJar) {
            Copy-Item $wrapperJar.FullName -Destination $output
            Write-Host "Successfully extracted gradle-wrapper.jar"
        } else {
            Write-Host "Error: Could not find gradle-wrapper.jar in extracted files"
            exit 1
        }
        
        Remove-Item $tempZip -Force -ErrorAction SilentlyContinue
        Remove-Item $tempDir -Recurse -Force -ErrorAction SilentlyContinue
    } catch {
        Write-Host "Error: $_"
        Write-Host "Please download gradle-wrapper.jar manually from:"
        Write-Host "https://github.com/gradle/gradle/tree/v8.9.0/gradle/wrapper"
        exit 1
    }
}

Write-Host ""
Write-Host "Done! Gradle wrapper setup complete."
Write-Host "Files created:"
Write-Host "  - gradlew"
Write-Host "  - gradlew.bat"
Write-Host "  - gradle\wrapper\gradle-wrapper.jar"